# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

# Deploy on push or pull request to main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    # Use the Ubuntu OS.
    runs-on: ubuntu-latest

    steps:
    # Use actions/checkout version 2. See https://github.com/actions/checkout
    - uses: actions/checkout@v2
    # Set up Python.
    - name: Set up Python 3.9
    # Use actions/setup-python version 2. See https://github.com/actions/setup-python
      uses: actions/setup-python@v2
      with:
        # Specify Python version.
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Flake8 looks for errors, Pytest runs tests.
        pip install flake8 pytest
        # Install dependencies if the requirements.txt file is found in repository.
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      # Run flake8.
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      # Run Pytest.
      run: |
        pytest -v
